import React from "react";
import { TrendingUp, Sparkles, ArrowRight, IndianRupee, AlertCircle, HelpCircle, CheckCircle } from "lucide-react";

export default function AdditionalRevenue({ economics, topCrop, farmerInput, onUpdateFarmerInput }) {
  if (!economics || !topCrop) return null;

  const {
    totalLand,
    hvLand,
    convLandOnly,
    primaryCrop,
    conventionalOnlyIncome,
    diversifiedIncome,
    additionalRevenue,
    percentageBoost,
  } = economics;

  return (
    <div className="revenue-highlight-section">
      <div className="revenue-banner-header">
        <div className="revenue-header-title">
          <div className="sparkle-circle">
            <Sparkles size={24} color="#ffffff" />
          </div>
          <div>
            <span className="revenue-kicker">KRISHI SETU DIVERSIFICATION IMPACT</span>
            <h2>Potential Additional Revenue Opportunity</h2>
          </div>
        </div>

        <div className="revenue-percentage-pill">
          <span>+{percentageBoost}%</span>
          <small>Net Income Boost</small>
        </div>
      </div>

      {/* Main Income Comparison Visual */}
      <div className="income-comparison-cards">
        {/* Card 1: 100% Conventional Crop Strategy */}
        <div className="income-card conventional-card">
          <div className="card-badge">CONVENTIONAL PLAN (100% LAND)</div>
          <h3>{primaryCrop} Only</h3>
          <p className="strategy-desc">
            Cultivating {primaryCrop} on entire {totalLand} Acres
          </p>

          <div className="income-amount-box">
            <span>Est. Net Income</span>
            <strong className="amount-value">₹{conventionalOnlyIncome.toLocaleString("en-IN")}</strong>
          </div>

          <div className="income-breakdown-list">
            <div className="breakdown-item">
              <span>Primary Land ({totalLand} Acres)</span>
              <span>₹{conventionalOnlyIncome.toLocaleString("en-IN")}</span>
            </div>
            <div className="breakdown-item">
              <span>High-Value Minor Crop</span>
              <span>₹0 (None)</span>
            </div>
          </div>
        </div>

        {/* Transition Arrow */}
        <div className="strategy-arrow">
          <ArrowRight size={28} />
          <span>DIVERSIFY</span>
        </div>

        {/* Card 2: KRISHI SETU Diversification Strategy */}
        <div className="income-card diversified-card">
          <div className="card-badge highlight-badge">KRISHI SETU SMART STRATEGY</div>
          <h3>
            {primaryCrop} + {topCrop.name} {topCrop.icon}
          </h3>
          <p className="strategy-desc">
            {convLandOnly.toFixed(2)} Acres {primaryCrop} + {hvLand} Acre High-Value {topCrop.name}
          </p>

          <div className="income-amount-box highlight-box">
            <span>Est. Net Income</span>
            <strong className="amount-value green">
              ₹{diversifiedIncome.toLocaleString("en-IN")}
            </strong>
          </div>

          <div className="income-breakdown-list">
            <div className="breakdown-item">
              <span>{primaryCrop} ({convLandOnly.toFixed(2)} Acres)</span>
              <span>₹{Math.round(convLandOnly * (conventionalOnlyIncome / totalLand)).toLocaleString("en-IN")}</span>
            </div>
            <div className="breakdown-item">
              <span>{topCrop.name} ({hvLand} Acre)</span>
              <span className="green">+₹{topCrop.estNetReturn.toLocaleString("en-IN")}</span>
            </div>
          </div>
        </div>

        {/* Card 3: Additional Revenue Difference Callout */}
        <div className="income-card difference-card">
          <div className="card-badge surge-badge">NET GAIN SURGE</div>
          <h3>Additional Revenue</h3>
          <p className="strategy-desc">Extra earnings generated by diversifying {hvLand} Acre</p>

          <div className="surge-amount-box">
            <span className="surge-label">+ ADDITIONAL INCOME</span>
            <strong className="surge-value">
              +₹{additionalRevenue.toLocaleString("en-IN")}
            </strong>
            <span className="surge-subtext">From suitable portion of land</span>
          </div>
        </div>
      </div>

      {/* Interactive Land Allocation Slider */}
      <div className="interactive-slider-box">
        <div className="slider-label-row">
          <span>
            <TrendingUp size={16} /> Adjust High-Value Crop Land Portion:
          </span>
          <strong>{hvLand} Acre Allocated</strong>
        </div>
        <input
          type="range"
          min="0.1"
          max={Math.min(totalLand, 3.0)}
          step="0.1"
          value={farmerInput.highValueLandAcres}
          onChange={(e) =>
            onUpdateFarmerInput({
              ...farmerInput,
              highValueLandAcres: parseFloat(e.target.value) || 0.1,
            })
          }
        />
        <div className="slider-footer-note">
          <HelpCircle size={14} />
          <span>
            Notice: Values are estimates based on average APMC mandi rates and historical yields. Actual revenue depends on market fluctuations, weather conditions, and farm management.
          </span>
        </div>
      </div>
    </div>
  );
}
